title: Cielo Loy
description: Aspiring Java Developer, Lifelong Learner, Creator
site_title: 'Cielo Loy'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: cieloaloy
linkedin_username: cieloloy
email: cieloaloy@gmail.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: G-RY31DGWHG4